[pytest]
# look for tests in the 'tests' directory
testpaths = tests

# add the current directory to Python’s import path
pythonpath = .

filterwarnings =
    # SQLAlchemy’s declarative_base deprecation
    ignore:.*declarative_base.*:DeprecationWarning
    # passlib’s crypt module deprecation
    ignore:.*crypt is deprecated.*:DeprecationWarning
    # Pydantic class‐based Config deprecation
    ignore:.*Support for class-based `config` is deprecated.*:DeprecationWarning
	ignore:.*'crypt' is deprecated.*:DeprecationWarning
	ignore:.*Query\.get\(\) method is considered legacy.*:sqlalchemy.exc.LegacyAPIWarning
	ignore:Valid config keys have changed in V2:UserWarning



